config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/FAQ'

  get 'static_pages/About'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :products
  
  resource :cart, only: [:show] do
  	post "add/:id", :as => "add", :action => "add"
  	post "remove/:id", :as => "remove", :action => "remove"
    post "decrement/:id", :as => "decrement", :action => "decrement"
    get :checkout
  	get :clear
  end

  resources :orders, only: [ :index, :show, :create, :update ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
end

app/models/cart.rb
class Cart
	attr_reader :items

	def self.build_from_hash hash
		items = 
		if hash["cart"] then
			hash["cart"]["items"].map do |item_data|
				CartItem.new item_data["product_id"], item_data["quantity"]
			end
		else
			[]
		end
		
		new items
	end

	def initialize items = []
		@items = items 
	end

	def add_item product_id
		item = @items.find { |item| item.product_id == product_id }
		if item
			item.increment
		else
			@items << CartItem.new(product_id)
		end
	end

	def decrement_quantity product_id
		item = @items.find { |item| item.product_id == product_id }
		if item.quantity > 1
			item.decrement
		else 
			remove_item(product_id)
		end
	end

	def remove_item product_id
		@items.delete_if { |item| item.product_id == product_id }
	end

	def count
		@items.length
	end

	def empty?
		@items.empty?
	end

	def serialize
		items = @items.map do |item| 
			{ 
				"product_id" => item.product_id, 
				"quantity" => item.quantity
			}
		end
		
		{
			"items" => items
		}
	end

	def total_price
		@items.inject(0) { |sum, item| sum + item.total_price }
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "Added #{product.name} to cart"
	end

	def remove
		@cart.remove_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "Removed #{product.name} from cart"
	end

	def decrement
		@cart.decrement_quantity params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "Changed quantity of #{product.name}"
	end

	def clear message = true
		session.delete(:cart)
		if message
			redirect_to :back, notice: "cart was cleared."
		end
	end

	def show		
	end

	def checkout
		if current_user
			@order_form = OrderForm.new user: current_user
		else
			@order_form = OrderForm.new user: User.new
		end
	end
end

app/views/carts/checkout.html.haml
%h1=t('.Checkout')

%h2=t('.Order_form_products')

%table.table.table-hover
	%thead
		%tr
			%td= t(".Quantity")
			%td= t(".Product")
			%td= t(".Subtotal")
		-@cart.items.each do |item|
			%tr
				%td=item.quantity
				%td
					%strong=item.product.name
				%td=number_to_currency(item.total_price, unit: "€ ")
		%tr 
			%td
			%td
				%strong
					=t('.Price_total')
			%td=number_to_currency(@cart.total_price, unit: '€ ')

=form_for @order_form, url: orders_path do |f|
	=render 'orders/errors'
	%h3=t(".Your_details")
	-if !current_user
		=f.fields_for :user, f.object.user do |u|
			.form-group
				%p=u.text_field :name, placeholder: t(".Name"), class: "form-control input-lg"
				%p
					=u.text_field :email, placeholder: t(".Email"), class: "form-control"
					%span.help-block=t('.Email_help')
				.form-group
					.row
						%p.col-md-6=u.text_field :address, placeholder: t(".Address"), class: "form-control"
						%p.col-md-3=u.text_field :postal_code, placeholder: t(".Postal_code"), class: "	form-control"
						%p.col-md-3=u.text_field :city, placeholder: t(".City"), class: "form-control"
					%p=u.country_select :country, { priority_countries: [ "BE" ] }, { class: "form-control" }
		
					%p
						=u.text_field :phone, class: "form-control", placeholder: t(".Phone")
						%span.help-block=t(".Phone_help")
	-else
		%address
			%strong=t(".Name")
			%strong : 
			%strong=current_user.name
			%br
			=t(".Address")
			\: 
			=simple_format current_user.full_address
		%p=link_to t(".Change_details"), edit_user_registration_path, class: "btn btn_primary"
	/%p=f.text_area :remark, placeholder: t('.Remarks'), class: "form-control"
	%p=f.submit t(".Place_order"), class: "btn btn_primary"

app/views/carts/show.html.haml
%h3 You are about to reserve:
%table.table.table-hover
	%thead
		%tr
			%td Quantity
			%td Product
			%td Price
			%td

	-@cart.items.each do |item|
		%tr
			%td
				=link_to "-", decrement_cart_path(item.product_id), method: :post, class: "btn"
				=item.quantity 
				=link_to "+", add_cart_path(item.product_id), method: :post, class: "btn"
			%td
				=image_tag item.product.image.thumb, height: 50
				=link_to item.product.name, item.product
			%td= number_to_currency(item.total_price, unit: '€ ')
			%td=link_to "Remove item", remove_cart_path(item.product_id), method: :post, class: "btn btn-primary"

%p.pull-right
	%strong	Total:
	=number_to_currency(@cart.total_price, unit: '€ ' )

%p=link_to "Checkout", checkout_cart_path, class: "btn btn-primary"
%p=link_to "Clear cart", clear_cart_path, class: "btn btn-primary"