config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/FAQ'

  get 'static_pages/About'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :products
  
  resource :cart, only: [:show] do
  	post "add/:id", :as => "add", :action => "add"
  	post "remove/:id", :as => "remove", :action => "remove"
    post "decrement/:id", :as => "decrement", :action => "decrement"
    get :checkout
  	get :clear
  end

  resources :orders, only: [ :index, :show, :create, :update ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :initialize_cart

  def initialize_cart
  	@cart = Cart.build_from_hash session  	
  end

  def authenticate_admin!
  	authenticate_user!

  	unless current_user.admin?
  		redirect_to root_path, alert: "You are not allowed to perform that operation"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.haml
-if @cart 
	%p.navbar-text.navbar-right
		-if @cart.empty?
			=t ('.cart_empty')
		-else
			=link_to t('.cart_items', count: @cart.count), cart_path

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Frais du jardin</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to t('.products'), products_path %></li>
        <% if current_user && current_user.admin? %>
          <li><%=link_to "Orders", orders_path %></li>
        <% end %>
        <li><%=link_to t('.FAQ'), static_pages_FAQ_path %></li>
        <li><%=link_to t('.About'), static_pages_About_path %></li>
      </ul>
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
          <%=t(".Logged_in_user", user: current_user.name) %>
          <%= link_to t(".Logout"), destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to t(".Login"), new_user_session_path, class: "navbar-link" %>
        <% end %>
      </p>
      <%= render "cart" %>
     <!--  for reference how to add different items

     <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>