config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/FAQ'

  get 'static_pages/About'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :products
  
  resource :cart, only: [:show] do
  	post "add/:id", :as => "add", :action => "add"
  	post "remove/:id", :as => "remove", :action => "remove"
    post "decrement/:id", :as => "decrement", :action => "decrement"
    get :checkout
  	get :clear
  end

  resources :orders, only: [ :index, :show, :create, :update ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader

	validates_presence_of :name, :price
	validates_numericality_of :price
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [ :new, :edit, :update, :create, :destroy ]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order('products.name DESC').all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :quantity)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for(product, multipart: true) do |f|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :quantity
    = f.number_field :quantity
  .actions
    = f.submit

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product
= link_to 'Show', @product
|
= link_to 'Back', products_path

app/views/products/index.html.haml
%p#notice= notice
%h1 Products

%p En dessous vous trouvez la liste des produits disponible, ajoutez-les a votre panier et completez la réservation. Vous recevez une notification quand les produits sont préparé.
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Price
      %th Image
      %th Quantity
      %th{:colspan => "3"}
  %tbody
    - @products.each do |product|
      -if product.quantity != 0 || current_user && current_user.admin?
        %tr
          %td= link_to product.name, product
          %td= simple_format(product.description)
          %td= number_to_currency(product.price, unit: '€ ')
          %td= image_tag product.image.thumb
          %td= product.quantity
          %td
            -if current_user && current_user.admin?
              = link_to 'Edit', edit_product_path(product)
              = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
            -else
              =link_to "Add to cart", add_cart_path(product), method: :post, class: "btn btn-primary"

-if current_user && current_user.admin?
  %p= link_to 'New Product', new_product_path, class: "btn  btn-primary"

app/views/products/new.html.haml
%h1 New Product
= render 'form', product: @product
= link_to 'Back', products_path

app/views/products/show.html.haml
%div.pull-left
  %h1= @product.name
  %p
    %strong Description:
    = simple_format(@product.description)
  %p= number_to_currency(@product.price, unit: '€ ')
  %p 
    Quantity:
    = @product.quantity

  %p=link_to "Add to cart", add_cart_path, method: :post, class: "btn btn-primary"
  -if current_user && current_user.admin?
    %p
      = link_to 'Edit', edit_product_path(@product), class: "btn btn-primary pull-left"
    
      = link_to 'Back', products_path, class: "btn btn-primary pull-left"
%p= image_tag @product.image, class: "pull-right", height: 300